import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
const CONTAINER_ID_PATTERN = /^[0-9a-f]{12,64}$/u;

interface MembershipFixture {
  id: string;
  tenantId: string;
  userId: string;
}

function assertUuid(value: string, label: string): void {
  if (!UUID_PATTERN.test(value)) {
    throw new Error(`${label} must be a UUID generated by the E2E runtime.`);
  }
}

/**
 * Creates only the state required to exercise deny-by-default. This is a
 * database fixture, not an invitation contract: production intentionally has
 * no membership-creation endpoint yet.
 */
export async function createMembershipWithoutRoles(input: MembershipFixture): Promise<void> {
  const containerId = process.env.E2E_POSTGRES_CONTAINER_ID;
  if (!containerId || !CONTAINER_ID_PATTERN.test(containerId)) {
    throw new Error("The E2E PostgreSQL container is not available to the test worker.");
  }

  assertUuid(input.id, "membershipId");
  assertUuid(input.tenantId, "tenantId");
  assertUuid(input.userId, "userId");

  const sql = `INSERT INTO "memberships" ("id", "tenant_id", "user_id", "status", "created_at", "updated_at") VALUES ('${input.id}'::uuid, '${input.tenantId}'::uuid, '${input.userId}'::uuid, 'ACTIVE', NOW(), NOW())`;
  await execFileAsync(
    "docker",
    [
      "exec",
      containerId,
      "psql",
      "-U",
      "erp_e2e",
      "-d",
      "erp_e2e",
      "-v",
      "ON_ERROR_STOP=1",
      "-c",
      sql,
    ],
    { timeout: 15_000 },
  );
}
